server:
  port: 8001
spring:
  application:
    name: order-center-job-consumer
  cloud:
    nacos:
      discovery:
        serverAddr: ${NACOS_SERVER_ADDR:}
        username: ${NACOS_SERVER_USERNAME:}
        password: ${NACOS_SERVER_PASSWORD:}

# 消费者将要去访问的微服务名称（注册成功的 Nacos 的微服务提供者）
providers:
  order-center-provider: http://order-center-provider